// Timeline data showing exponential project growth over time
const timelineData = {
    messy: [
        // Month 1 - Clean start (5 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 }
        ],
        // Month 2 - First additions (8 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 }
        ],
        // Month 4 - Growing complexity (15 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'api-helpers.js', type: 'file', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 }
        ],
        // Month 6 - Feature expansion (28 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'api-helpers.js', type: 'file', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-service.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'more-styles.css', type: 'file', level: 1 },
            { name: 'constants.js', type: 'config', level: 1 },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'theme.css', type: 'file', level: 1 }
        ],
        // Month 9 - Multiple developers, duplicates emerge (65 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'Button2.js', type: 'component', level: 1, duplicate: true },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-new.js', type: 'file', level: 1, duplicate: true },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'more-styles.css', type: 'file', level: 1 },
            { name: 'new-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'api-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'helper-functions.js', type: 'file', level: 1, duplicate: true },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'LoginForm-old.js', type: 'component', level: 1, duplicate: true },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'app-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'constants.js', type: 'config', level: 1, duplicate: true },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'theme.css', type: 'file', level: 1 },
            { name: 'SearchPage.js', type: 'component', level: 1 },
            { name: 'Filters.js', type: 'component', level: 1 },
            { name: 'search-helpers.js', type: 'file', level: 1 },
            { name: 'pagination.js', type: 'file', level: 1 },
            { name: 'sorting.js', type: 'file', level: 1 },
            { name: 'filters-data.js', type: 'file', level: 1 },
            { name: 'search-config.js', type: 'config', level: 1 },
            { name: 'Navbar.js', type: 'component', level: 1 },
            { name: 'Footer.js', type: 'component', level: 1 },
            { name: 'LoadingSpinner.js', type: 'component', level: 1 },
            { name: 'ErrorBoundary.js', type: 'component', level: 1 },
            { name: 'Toast.js', type: 'component', level: 1 },
            { name: 'Table.js', type: 'component', level: 1 },
            { name: 'Card.js', type: 'component', level: 1 },
            { name: 'Input.js', type: 'component', level: 1 },
            { name: 'Select.js', type: 'component', level: 1 },
            { name: 'Checkbox.js', type: 'component', level: 1 },
            { name: 'Radio.js', type: 'component', level: 1 },
            { name: 'Textarea.js', type: 'component', level: 1 },
            { name: 'PasswordInput.js', type: 'component', level: 1 },
            { name: 'DatePicker.js', type: 'component', level: 1 },
            { name: 'TimePicker.js', type: 'component', level: 1 },
            { name: 'ColorPicker.js', type: 'component', level: 1 },
            { name: 'FileUpload.js', type: 'component', level: 1 },
            { name: 'ImageUpload.js', type: 'component', level: 1 },
            { name: 'ProgressBar.js', type: 'component', level: 1 },
            { name: 'Slider.js', type: 'component', level: 1 },
            { name: 'Toggle.js', type: 'component', level: 1 },
            { name: 'Tooltip.js', type: 'component', level: 1 },
            { name: 'Dropdown.js', type: 'component', level: 1 },
            { name: 'Accordion.js', type: 'component', level: 1 },
            { name: 'Tabs.js', type: 'component', level: 1 }
        ],
        // Month 12 - Technical debt accumulates (120 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'App-backup.js', type: 'file', level: 1, duplicate: true },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'Button2.js', type: 'component', level: 1, duplicate: true },
            { name: 'ButtonNew.js', type: 'component', level: 1, duplicate: true },
            { name: 'ButtonOld.js', type: 'component', level: 1, duplicate: true },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils3.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-new.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-backup.js', type: 'file', level: 1, duplicate: true },
            { name: 'utilities.js', type: 'file', level: 1, duplicate: true },
            { name: 'common-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'more-styles.css', type: 'file', level: 1 },
            { name: 'new-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'theme.css', type: 'file', level: 1, duplicate: true },
            { name: 'global.css', type: 'file', level: 1, duplicate: true },
            { name: 'app-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'Header-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'HomePage-old.js', type: 'component', level: 1, duplicate: true },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'api-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-client.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'apiService.js', type: 'file', level: 1, duplicate: true },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'data-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers3.js', type: 'file', level: 1, duplicate: true },
            { name: 'helper-functions.js', type: 'file', level: 1, duplicate: true },
            { name: 'help.js', type: 'file', level: 1, duplicate: true },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'LoginForm-old.js', type: 'component', level: 1, duplicate: true },
            { name: 'LoginForm-new.js', type: 'component', level: 1, duplicate: true },
            { name: 'Login.js', type: 'component', level: 1, duplicate: true },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'app-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'prod-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'dev-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'test-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'constants.js', type: 'config', level: 1, duplicate: true },
            { name: 'CONSTANTS.js', type: 'config', level: 1, duplicate: true },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'Profile.js', type: 'component', level: 1, duplicate: true },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'DashboardNew.js', type: 'component', level: 1, duplicate: true },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'Modal2.js', type: 'component', level: 1, duplicate: true },
            { name: 'ModalComponent.js', type: 'component', level: 1, duplicate: true },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'SettingsPage.js', type: 'component', level: 1, duplicate: true },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'SideNav.js', type: 'component', level: 1, duplicate: true },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'formUtils.js', type: 'file', level: 1, duplicate: true },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'auth-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'authentication.js', type: 'file', level: 1, duplicate: true },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'validate.js', type: 'file', level: 1, duplicate: true },
            { name: 'validators.js', type: 'file', level: 1, duplicate: true },
            { name: 'SearchPage.js', type: 'component', level: 1 },
            { name: 'Search.js', type: 'component', level: 1, duplicate: true },
            { name: 'Filters.js', type: 'component', level: 1 },
            { name: 'FilterPanel.js', type: 'component', level: 1, duplicate: true },
            { name: 'search-helpers.js', type: 'file', level: 1 },
            { name: 'searchUtils.js', type: 'file', level: 1, duplicate: true },
            { name: 'pagination.js', type: 'file', level: 1 },
            { name: 'paginate.js', type: 'file', level: 1, duplicate: true },
            { name: 'sorting.js', type: 'file', level: 1 },
            { name: 'sort.js', type: 'file', level: 1, duplicate: true },
            { name: 'filters-data.js', type: 'file', level: 1 },
            { name: 'search-config.js', type: 'config', level: 1 },
            { name: 'Navbar.js', type: 'component', level: 1 },
            { name: 'Navigation.js', type: 'component', level: 1, duplicate: true },
            { name: 'NavBar.js', type: 'component', level: 1, duplicate: true },
            { name: 'Footer.js', type: 'component', level: 1 },
            { name: 'LoadingSpinner.js', type: 'component', level: 1 },
            { name: 'Spinner.js', type: 'component', level: 1, duplicate: true },
            { name: 'Loading.js', type: 'component', level: 1, duplicate: true },
            { name: 'ErrorBoundary.js', type: 'component', level: 1 },
            { name: 'Error.js', type: 'component', level: 1, duplicate: true },
            { name: 'Toast.js', type: 'component', level: 1 },
            { name: 'Notification.js', type: 'component', level: 1, duplicate: true },
            { name: 'Alert.js', type: 'component', level: 1, duplicate: true },
            { name: 'Table.js', type: 'component', level: 1 },
            { name: 'DataTable.js', type: 'component', level: 1, duplicate: true },
            { name: 'Card.js', type: 'component', level: 1 },
            { name: 'CardComponent.js', type: 'component', level: 1, duplicate: true },
            { name: 'Input.js', type: 'component', level: 1 },
            { name: 'InputField.js', type: 'component', level: 1, duplicate: true },
            { name: 'TextInput.js', type: 'component', level: 1, duplicate: true },
            { name: 'Select.js', type: 'component', level: 1 },
            { name: 'SelectBox.js', type: 'component', level: 1, duplicate: true },
            { name: 'Dropdown.js', type: 'component', level: 1, duplicate: true },
            { name: 'DropdownMenu.js', type: 'component', level: 1, duplicate: true },
            { name: 'Checkbox.js', type: 'component', level: 1 },
            { name: 'CheckBox.js', type: 'component', level: 1, duplicate: true },
            { name: 'Radio.js', type: 'component', level: 1 },
            { name: 'RadioButton.js', type: 'component', level: 1, duplicate: true },
            { name: 'Textarea.js', type: 'component', level: 1 },
            { name: 'TextArea.js', type: 'component', level: 1, duplicate: true },
            { name: 'PasswordInput.js', type: 'component', level: 1 },
            { name: 'Password.js', type: 'component', level: 1, duplicate: true },
            { name: 'DatePicker.js', type: 'component', level: 1 },
            { name: 'DateInput.js', type: 'component', level: 1, duplicate: true },
            { name: 'TimePicker.js', type: 'component', level: 1 },
            { name: 'TimeInput.js', type: 'component', level: 1, duplicate: true },
            { name: 'ColorPicker.js', type: 'component', level: 1 },
            { name: 'FileUpload.js', type: 'component', level: 1 },
            { name: 'Upload.js', type: 'component', level: 1, duplicate: true },
            { name: 'ImageUpload.js', type: 'component', level: 1 },
            { name: 'ProgressBar.js', type: 'component', level: 1 },
            { name: 'Progress.js', type: 'component', level: 1, duplicate: true },
            { name: 'Slider.js', type: 'component', level: 1 },
            { name: 'RangeSlider.js', type: 'component', level: 1, duplicate: true },
            { name: 'Toggle.js', type: 'component', level: 1 },
            { name: 'Switch.js', type: 'component', level: 1, duplicate: true },
            { name: 'Tooltip.js', type: 'component', level: 1 },
            { name: 'ToolTip.js', type: 'component', level: 1, duplicate: true },
            { name: 'Accordion.js', type: 'component', level: 1 },
            { name: 'Tabs.js', type: 'component', level: 1 },
            { name: 'TabPanel.js', type: 'component', level: 1, duplicate: true }
        ],
        // Month 18 - Complete chaos (280+ files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'App-backup.js', type: 'file', level: 1, duplicate: true },
            { name: 'App-old.js', type: 'file', level: 1, duplicate: true },
            { name: 'App-v2.js', type: 'file', level: 1, duplicate: true },
            { name: 'app.js', type: 'file', level: 1, duplicate: true },
            { name: 'main.js', type: 'file', level: 1, duplicate: true },
            { name: 'index.js', type: 'file', level: 1, duplicate: true },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'Button2.js', type: 'component', level: 1, duplicate: true },
            { name: 'Button3.js', type: 'component', level: 1, duplicate: true },
            { name: 'ButtonNew.js', type: 'component', level: 1, duplicate: true },
            { name: 'ButtonOld.js', type: 'component', level: 1, duplicate: true },
            { name: 'button.js', type: 'component', level: 1, duplicate: true },
            { name: 'btn.js', type: 'component', level: 1, duplicate: true },
            { name: 'MyButton.js', type: 'component', level: 1, duplicate: true },
            { name: 'CustomButton.js', type: 'component', level: 1, duplicate: true },
            { name: 'PrimaryButton.js', type: 'component', level: 1, duplicate: true },
            { name: 'SecondaryButton.js', type: 'component', level: 1, duplicate: true },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils3.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils4.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-new.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-old.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-backup.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-temp.js', type: 'file', level: 1, duplicate: true },
            { name: 'utilities.js', type: 'file', level: 1, duplicate: true },
            { name: 'common-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'shared-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'global-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'misc-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'random-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'styles2.css', type: 'file', level: 1, duplicate: true },
            { name: 'more-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'new-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'old-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'main-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'theme.css', type: 'file', level: 1, duplicate: true },
            { name: 'theme-dark.css', type: 'file', level: 1, duplicate: true },
            { name: 'theme-light.css', type: 'file', level: 1, duplicate: true },
            { name: 'global.css', type: 'file', level: 1, duplicate: true },
            { name: 'app-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'custom.css', type: 'file', level: 1, duplicate: true },
            { name: 'responsive.css', type: 'file', level: 1, duplicate: true },
            { name: 'mobile.css', type: 'file', level: 1, duplicate: true },
            { name: 'desktop.css', type: 'file', level: 1, duplicate: true },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'Header-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'Header-v3.js', type: 'component', level: 1, duplicate: true },
            { name: 'HeaderNew.js', type: 'component', level: 1, duplicate: true },
            { name: 'HeaderOld.js', type: 'component', level: 1, duplicate: true },
            { name: 'AppHeader.js', type: 'component', level: 1, duplicate: true },
            { name: 'MainHeader.js', type: 'component', level: 1, duplicate: true },
            { name: 'TopNav.js', type: 'component', level: 1, duplicate: true },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'HomePage-old.js', type: 'component', level: 1, duplicate: true },
            { name: 'HomePage-new.js', type: 'component', level: 1, duplicate: true },
            { name: 'Home.js', type: 'component', level: 1, duplicate: true },
            { name: 'HomePageComponent.js', type: 'component', level: 1, duplicate: true },
            { name: 'Landing.js', type: 'component', level: 1, duplicate: true },
            { name: 'LandingPage.js', type: 'component', level: 1, duplicate: true },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'api-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-client.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-old.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-new.js', type: 'file', level: 1, duplicate: true },
            { name: 'apiService.js', type: 'file', level: 1, duplicate: true },
            { name: 'apiClient.js', type: 'file', level: 1, duplicate: true },
            { name: 'rest-api.js', type: 'file', level: 1, duplicate: true },
            { name: 'fetch-api.js', type: 'file', level: 1, duplicate: true },
            { name: 'ajax-calls.js', type: 'file', level: 1, duplicate: true },
            { name: 'http-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'backend-api.js', type: 'file', level: 1, duplicate: true },
            { name: 'server-api.js', type: 'file', level: 1, duplicate: true },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'data-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'data-store.js', type: 'file', level: 1, duplicate: true },
            { name: 'data-manager.js', type: 'file', level: 1, duplicate: true },
            { name: 'dataService.js', type: 'file', level: 1, duplicate: true },
            { name: 'mockData.js', type: 'file', level: 1, duplicate: true },
            { name: 'testData.js', type: 'file', level: 1, duplicate: true },
            { name: 'sample-data.js', type: 'file', level: 1, duplicate: true },
            { name: 'dummy-data.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers3.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers4.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers-new.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers-old.js', type: 'file', level: 1, duplicate: true },
            { name: 'helper-functions.js', type: 'file', level: 1, duplicate: true },
            { name: 'help.js', type: 'file', level: 1, duplicate: true },
            { name: 'helperfuncs.js', type: 'file', level: 1, duplicate: true },
            { name: 'support.js', type: 'file', level: 1, duplicate: true },
            { name: 'tools.js', type: 'file', level: 1, duplicate: true },
            { name: 'functions.js', type: 'file', level: 1, duplicate: true },
            { name: 'common.js', type: 'file', level: 1, duplicate: true },
            { name: 'shared.js', type: 'file', level: 1, duplicate: true },
            { name: 'misc.js', type: 'file', level: 1, duplicate: true },
            { name: 'extra.js', type: 'file', level: 1, duplicate: true },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'LoginForm-old.js', type: 'component', level: 1, duplicate: true },
            { name: 'LoginForm-new.js', type: 'component', level: 1, duplicate: true },
            { name: 'LoginForm-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'Login.js', type: 'component', level: 1, duplicate: true },
            { name: 'LoginPage.js', type: 'component', level: 1, duplicate: true },
            { name: 'SignIn.js', type: 'component', level: 1, duplicate: true },
            { name: 'SignInForm.js', type: 'component', level: 1, duplicate: true },
            { name: 'Auth.js', type: 'component', level: 1, duplicate: true },
            { name: 'AuthForm.js', type: 'component', level: 1, duplicate: true },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'app-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'prod-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'dev-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'test-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'staging-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'local-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'environment.js', type: 'config', level: 1, duplicate: true },
            { name: 'env.js', type: 'config', level: 1, duplicate: true },
            { name: 'settings.js', type: 'config', level: 1, duplicate: true },
            { name: 'constants.js', type: 'config', level: 1, duplicate: true },
            { name: 'CONSTANTS.js', type: 'config', level: 1, duplicate: true },
            { name: 'Constants.js', type: 'config', level: 1, duplicate: true },
            { name: 'const.js', type: 'config', level: 1, duplicate: true },
            { name: 'vars.js', type: 'config', level: 1, duplicate: true },
            { name: 'variables.js', type: 'config', level: 1, duplicate: true },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'UserProfile-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'Profile.js', type: 'component', level: 1, duplicate: true },
            { name: 'ProfilePage.js', type: 'component', level: 1, duplicate: true },
            { name: 'User.js', type: 'component', level: 1, duplicate: true },
            { name: 'UserPage.js', type: 'component', level: 1, duplicate: true },
            { name: 'Account.js', type: 'component', level: 1, duplicate: true },
            { name: 'AccountPage.js', type: 'component', level: 1, duplicate: true },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'Dashboard-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'DashboardNew.js', type: 'component', level: 1, duplicate: true },
            { name: 'DashboardOld.js', type: 'component', level: 1, duplicate: true },
            { name: 'AdminDashboard.js', type: 'component', level: 1, duplicate: true },
            { name: 'UserDashboard.js', type: 'component', level: 1, duplicate: true },
            { name: 'MainDashboard.js', type: 'component', level: 1, duplicate: true },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'Modal2.js', type: 'component', level: 1, duplicate: true },
            { name: 'Modal3.js', type: 'component', level: 1, duplicate: true },
            { name: 'ModalComponent.js', type: 'component', level: 1, duplicate: true },
            { name: 'ModalDialog.js', type: 'component', level: 1, duplicate: true },
            { name: 'Dialog.js', type: 'component', level: 1, duplicate: true },
            { name: 'Popup.js', type: 'component', level: 1, duplicate: true },
            { name: 'PopupModal.js', type: 'component', level: 1, duplicate: true },
            { name: 'Overlay.js', type: 'component', level: 1, duplicate: true },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'Settings-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'SettingsPage.js', type: 'component', level: 1, duplicate: true },
            { name: 'SettingsPanel.js', type: 'component', level: 1, duplicate: true },
            { name: 'Configuration.js', type: 'component', level: 1, duplicate: true },
            { name: 'Config.js', type: 'component', level: 1, duplicate: true },
            { name: 'Preferences.js', type: 'component', level: 1, duplicate: true },
            { name: 'Options.js', type: 'component', level: 1, duplicate: true },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'Sidebar-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'SideNav.js', type: 'component', level: 1, duplicate: true },
            { name: 'SidePanel.js', type: 'component', level: 1, duplicate: true },
            { name: 'LeftSidebar.js', type: 'component', level: 1, duplicate: true },
            { name: 'RightSidebar.js', type: 'component', level: 1, duplicate: true },
            { name: 'Navigation.js', type: 'component', level: 1, duplicate: true },
            { name: 'Nav.js', type: 'component', level: 1, duplicate: true },
            { name: 'Menu.js', type: 'component', level: 1, duplicate: true },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'form-validation.js', type: 'file', level: 1, duplicate: true },
            { name: 'formUtils.js', type: 'file', level: 1, duplicate: true },
            { name: 'formHelpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'forms.js', type: 'file', level: 1, duplicate: true },
            { name: 'form-handler.js', type: 'file', level: 1, duplicate: true },
            { name: 'form-manager.js', type: 'file', level: 1, duplicate: true },
            { name: 'form-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'auth-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'auth-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'authentication.js', type: 'file', level: 1, duplicate: true },
            { name: 'authService.js', type: 'file', level: 1, duplicate: true },
            { name: 'authHelpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'login-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'session.js', type: 'file', level: 1, duplicate: true },
            { name: 'token.js', type: 'file', level: 1, duplicate: true },
            { name: 'jwt.js', type: 'file', level: 1, duplicate: true },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'validate.js', type: 'file', level: 1, duplicate: true },
            { name: 'validators.js', type: 'file', level: 1, duplicate: true },
            { name: 'validator.js', type: 'file', level: 1, duplicate: true },
            { name: 'form-validation.js', type: 'file', level: 1, duplicate: true },
            { name: 'input-validation.js', type: 'file', level: 1, duplicate: true },
            { name: 'field-validation.js', type: 'file', level: 1, duplicate: true },
            { name: 'rules.js', type: 'file', level: 1, duplicate: true },
            { name: 'schema.js', type: 'file', level: 1, duplicate: true },
            { name: 'SearchPage.js', type: 'component', level: 1 },
            { name: 'SearchPage-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'Search.js', type: 'component', level: 1, duplicate: true },
            { name: 'SearchComponent.js', type: 'component', level: 1, duplicate: true },
            { name: 'SearchContainer.js', type: 'component', level: 1, duplicate: true },
            { name: 'SearchView.js', type: 'component', level: 1, duplicate: true },
            { name: 'SearchResults.js', type: 'component', level: 1, duplicate: true },
            { name: 'Results.js', type: 'component', level: 1, duplicate: true },
            { name: 'Filters.js', type: 'component', level: 1 },
            { name: 'Filters-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'FilterPanel.js', type: 'component', level: 1, duplicate: true },
            { name: 'FilterComponent.js', type: 'component', level: 1, duplicate: true },
            { name: 'FilterBar.js', type: 'component', level: 1, duplicate: true },
            { name: 'FilterSidebar.js', type: 'component', level: 1, duplicate: true },
            { name: 'search-helpers.js', type: 'file', level: 1 },
            { name: 'search-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'searchUtils.js', type: 'file', level: 1, duplicate: true },
            { name: 'searchHelpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'search-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'searchService.js', type: 'file', level: 1, duplicate: true },
            { name: 'search-api.js', type: 'file', level: 1, duplicate: true },
            { name: 'search-engine.js', type: 'file', level: 1, duplicate: true },
            { name: 'query-builder.js', type: 'file', level: 1, duplicate: true },
            { name: 'pagination.js', type: 'file', level: 1 },
            { name: 'paginate.js', type: 'file', level: 1, duplicate: true },
            { name: 'pager.js', type: 'file', level: 1, duplicate: true },
            { name: 'page-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'pagination-helper.js', type: 'file', level: 1, duplicate: true },
            { name: 'page-manager.js', type: 'file', level: 1, duplicate: true },
            { name: 'sorting.js', type: 'file', level: 1 },
            { name: 'sort.js', type: 'file', level: 1, duplicate: true },
            { name: 'sorter.js', type: 'file', level: 1, duplicate: true },
            { name: 'sort-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'sort-helper.js', type: 'file', level: 1, duplicate: true },
            { name: 'order.js', type: 'file', level: 1, duplicate: true },
            { name: 'ordering.js', type: 'file', level: 1, duplicate: true },
            { name: 'filters-data.js', type: 'file', level: 1 },
            { name: 'filter-data.js', type: 'file', level: 1, duplicate: true },
            { name: 'filter-options.js', type: 'file', level: 1, duplicate: true },
            { name: 'search-config.js', type: 'config', level: 1 },
            { name: 'search-settings.js', type: 'config', level: 1, duplicate: true },
            { name: 'filter-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'temp-file.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'temp2.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'test.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'test2.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'backup.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'old-code.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'legacy.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'deprecated.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'unused.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'dont-delete.js', type: 'file', level: 1, duplicate: true, problematic: 'problematic' },
            { name: 'working.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'broken.js', type: 'file', level: 1, duplicate: true, problematic: 'problematic' },
            { name: 'fix-later.js', type: 'file', level: 1, duplicate: true, problematic: 'problematic' },
            { name: 'todo.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'debug.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'console-log-test.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'random-stuff.js', type: 'file', level: 1, duplicate: true, problematic: 'problematic' },
            { name: 'misc-functions.js', type: 'file', level: 1, duplicate: true, problematic: 'problematic' },
            { name: 'experimental.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'playground.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'sandbox.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'scratchpad.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'notes.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'ideas.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'draft.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'wip.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'untitled.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'untitled-1.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'untitled-2.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'copy.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'copy-2.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'BACKUP-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'BACKUP-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'OLD-Button.js', type: 'component', level: 1, duplicate: true },
            { name: 'OLD-Modal.js', type: 'component', level: 1, duplicate: true },
            { name: 'NEW-Button.js', type: 'component', level: 1, duplicate: true },
            { name: 'NEW-Modal.js', type: 'component', level: 1, duplicate: true },
            { name: 'FINAL-Button.js', type: 'component', level: 1, duplicate: true },
            { name: 'WORKING-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'FIXED-api.js', type: 'file', level: 1, duplicate: true },
            { name: 'LATEST-config.js', type: 'config', level: 1, duplicate: true }
        ]
    ],
    organized: [
        // Month 1
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 3
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 6
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 9
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'UserProfile/', type: 'folder', level: 2 },
            { name: 'UserProfile.jsx', type: 'component', level: 3 },
            { name: 'Dashboard/', type: 'folder', level: 2 },
            { name: 'Dashboard.jsx', type: 'component', level: 3 },
            { name: 'Modal/', type: 'folder', level: 2 },
            { name: 'Modal.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'userService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'constants.js', type: 'config', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 12
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'UserProfile/', type: 'folder', level: 2 },
            { name: 'UserProfile.jsx', type: 'component', level: 3 },
            { name: 'Dashboard/', type: 'folder', level: 2 },
            { name: 'Dashboard.jsx', type: 'component', level: 3 },
            { name: 'Modal/', type: 'folder', level: 2 },
            { name: 'Modal.jsx', type: 'component', level: 3 },
            { name: 'Settings/', type: 'folder', level: 2 },
            { name: 'Settings.jsx', type: 'component', level: 3 },
            { name: 'Sidebar/', type: 'folder', level: 2 },
            { name: 'Sidebar.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'userService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'authUtils.js', type: 'file', level: 2 },
            { name: 'validation.js', type: 'file', level: 2 },
            { name: 'constants.js', type: 'config', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 },
            { name: 'theme.config.js', type: 'config', level: 2 }
        ],
        // Month 18
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'UserProfile/', type: 'folder', level: 2 },
            { name: 'UserProfile.jsx', type: 'component', level: 3 },
            { name: 'Dashboard/', type: 'folder', level: 2 },
            { name: 'Dashboard.jsx', type: 'component', level: 3 },
            { name: 'Modal/', type: 'folder', level: 2 },
            { name: 'Modal.jsx', type: 'component', level: 3 },
            { name: 'Settings/', type: 'folder', level: 2 },
            { name: 'Settings.jsx', type: 'component', level: 3 },
            { name: 'Sidebar/', type: 'folder', level: 2 },
            { name: 'Sidebar.jsx', type: 'component', level: 3 },
            { name: 'SearchPage/', type: 'folder', level: 2 },
            { name: 'SearchPage.jsx', type: 'component', level: 3 },
            { name: 'Filters/', type: 'folder', level: 2 },
            { name: 'Filters.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'userService.js', type: 'file', level: 3 },
            { name: 'searchService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'authUtils.js', type: 'file', level: 2 },
            { name: 'validation.js', type: 'file', level: 2 },
            { name: 'searchUtils.js', type: 'file', level: 2 },
            { name: 'pagination.js', type: 'file', level: 2 },
            { name: 'constants.js', type: 'config', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 },
            { name: 'theme.config.js', type: 'config', level: 2 },
            { name: 'search.config.js', type: 'config', level: 2 }
        ]
    ]
};

