// Timeline data showing exponential project growth over time
const timelineData = {
    messy: [
        // Month 1 - Clean start (5 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 }
        ],
        // Month 2 - First additions (8 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 }
        ],
        // Month 4 - Growing complexity (15 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'api-helpers.js', type: 'file', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 }
        ],
        // Month 6 - Feature expansion, first duplicates (28 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'api-helpers.js', type: 'file', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-service.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'more-styles.css', type: 'file', level: 1 },
            { name: 'constants.js', type: 'config', level: 1 },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'theme.css', type: 'file', level: 1 }
        ],
        // Month 9 - Multiple developers, duplicates emerge (45 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'Button2.js', type: 'component', level: 1, duplicate: true },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-new.js', type: 'file', level: 1, duplicate: true },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'more-styles.css', type: 'file', level: 1 },
            { name: 'new-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'api-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'helper-functions.js', type: 'file', level: 1, duplicate: true },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'LoginForm-old.js', type: 'component', level: 1, duplicate: true },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'app-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'constants.js', type: 'config', level: 1, duplicate: true },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'theme.css', type: 'file', level: 1 },
            { name: 'SearchPage.js', type: 'component', level: 1 },
            { name: 'Filters.js', type: 'component', level: 1 },
            { name: 'search-helpers.js', type: 'file', level: 1 },
            { name: 'pagination.js', type: 'file', level: 1 },
            { name: 'sorting.js', type: 'file', level: 1 },
            { name: 'filters-data.js', type: 'file', level: 1 },
            { name: 'search-config.js', type: 'config', level: 1 },
            { name: 'Navbar.js', type: 'component', level: 1 },
            { name: 'Footer.js', type: 'component', level: 1 },
            { name: 'LoadingSpinner.js', type: 'component', level: 1 },
            { name: 'Toast.js', type: 'component', level: 1 },
            { name: 'Table.js', type: 'component', level: 1 },
            { name: 'Card.js', type: 'component', level: 1 },
            { name: 'Input.js', type: 'component', level: 1 },
            { name: 'Select.js', type: 'component', level: 1 },
            { name: 'Button-old.js', type: 'component', level: 1, duplicate: true },
            { name: 'temp-modal.js', type: 'component', level: 1, duplicate: true, problematic: 'temp' }
        ],
        // Month 12 - Technical debt accumulates (65 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'App-backup.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'Button2.js', type: 'component', level: 1, duplicate: true },
            { name: 'ButtonOld.js', type: 'component', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-backup.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'utilities.js', type: 'file', level: 1, duplicate: true },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'more-styles.css', type: 'file', level: 1 },
            { name: 'new-styles.css', type: 'file', level: 1, duplicate: true },
            { name: 'theme.css', type: 'file', level: 1, duplicate: true },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'Header-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'HomePage-old.js', type: 'component', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'api-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'apiService.js', type: 'file', level: 1, duplicate: true },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'data-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'helper-functions.js', type: 'file', level: 1, duplicate: true },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'LoginForm-old.js', type: 'component', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'Login.js', type: 'component', level: 1, duplicate: true },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'app-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'dev-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'constants.js', type: 'config', level: 1, duplicate: true },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'Profile.js', type: 'component', level: 1, duplicate: true },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'DashboardNew.js', type: 'component', level: 1, duplicate: true },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'Modal2.js', type: 'component', level: 1, duplicate: true },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'SettingsPage.js', type: 'component', level: 1, duplicate: true },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'SideNav.js', type: 'component', level: 1, duplicate: true },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'auth-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'validate.js', type: 'file', level: 1, duplicate: true },
            { name: 'SearchPage.js', type: 'component', level: 1 },
            { name: 'Search.js', type: 'component', level: 1, duplicate: true },
            { name: 'Filters.js', type: 'component', level: 1 },
            { name: 'FilterPanel.js', type: 'component', level: 1, duplicate: true },
            { name: 'search-helpers.js', type: 'file', level: 1 },
            { name: 'searchUtils.js', type: 'file', level: 1, duplicate: true },
            { name: 'pagination.js', type: 'file', level: 1 },
            { name: 'paginate.js', type: 'file', level: 1, duplicate: true },
            { name: 'sorting.js', type: 'file', level: 1 },
            { name: 'sort.js', type: 'file', level: 1, duplicate: true },
            { name: 'filters-data.js', type: 'file', level: 1 },
            { name: 'search-config.js', type: 'config', level: 1 },
            { name: 'Navbar.js', type: 'component', level: 1 },
            { name: 'Navigation.js', type: 'component', level: 1, duplicate: true },
            { name: 'Footer.js', type: 'component', level: 1 },
            { name: 'LoadingSpinner.js', type: 'component', level: 1 },
            { name: 'Spinner.js', type: 'component', level: 1, duplicate: true },
            { name: 'Toast.js', type: 'component', level: 1 },
            { name: 'temp-test.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'debug-utils.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' }
        ],
        // Month 18 - Unorganized but realistic (85 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'App-backup.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'App-old.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'Button2.js', type: 'component', level: 1, duplicate: true },
            { name: 'ButtonOld.js', type: 'component', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils3.js', type: 'file', level: 1, duplicate: true },
            { name: 'utils-backup.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'utilities.js', type: 'file', level: 1, duplicate: true },
            { name: 'common-utils.js', type: 'file', level: 1, duplicate: true },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'styles2.css', type: 'file', level: 1, duplicate: true },
            { name: 'theme.css', type: 'file', level: 1, duplicate: true },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'Header-v2.js', type: 'component', level: 1, duplicate: true },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'HomePage-old.js', type: 'component', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'api-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'apiService.js', type: 'file', level: 1, duplicate: true },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'data-service.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'helpers3.js', type: 'file', level: 1, duplicate: true },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'LoginForm-old.js', type: 'component', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'Login.js', type: 'component', level: 1, duplicate: true },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'app-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'dev-config.js', type: 'config', level: 1, duplicate: true },
            { name: 'constants.js', type: 'config', level: 1, duplicate: true },
            { name: 'CONSTANTS.js', type: 'config', level: 1, duplicate: true },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'Profile.js', type: 'component', level: 1, duplicate: true },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'DashboardNew.js', type: 'component', level: 1, duplicate: true },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'Modal2.js', type: 'component', level: 1, duplicate: true },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'SettingsPage.js', type: 'component', level: 1, duplicate: true },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'SideNav.js', type: 'component', level: 1, duplicate: true },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'auth-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'validate.js', type: 'file', level: 1, duplicate: true },
            { name: 'SearchPage.js', type: 'component', level: 1 },
            { name: 'Search.js', type: 'component', level: 1, duplicate: true },
            { name: 'Filters.js', type: 'component', level: 1 },
            { name: 'FilterPanel.js', type: 'component', level: 1, duplicate: true },
            { name: 'search-helpers.js', type: 'file', level: 1 },
            { name: 'searchUtils.js', type: 'file', level: 1, duplicate: true },
            { name: 'pagination.js', type: 'file', level: 1 },
            { name: 'paginate.js', type: 'file', level: 1, duplicate: true },
            { name: 'sorting.js', type: 'file', level: 1 },
            { name: 'sort.js', type: 'file', level: 1, duplicate: true },
            { name: 'filters-data.js', type: 'file', level: 1 },
            { name: 'search-config.js', type: 'config', level: 1 },
            { name: 'Navbar.js', type: 'component', level: 1 },
            { name: 'Navigation.js', type: 'component', level: 1, duplicate: true },
            { name: 'Footer.js', type: 'component', level: 1 },
            { name: 'LoadingSpinner.js', type: 'component', level: 1 },
            { name: 'Spinner.js', type: 'component', level: 1, duplicate: true },
            { name: 'Toast.js', type: 'component', level: 1 },
            { name: 'Alert.js', type: 'component', level: 1, duplicate: true },
            { name: 'Table.js', type: 'component', level: 1 },
            { name: 'DataTable.js', type: 'component', level: 1, duplicate: true },
            { name: 'Card.js', type: 'component', level: 1 },
            { name: 'Input.js', type: 'component', level: 1 },
            { name: 'InputField.js', type: 'component', level: 1, duplicate: true },
            { name: 'Select.js', type: 'component', level: 1 },
            { name: 'Dropdown.js', type: 'component', level: 1, duplicate: true },
            { name: 'Checkbox.js', type: 'component', level: 1 },
            { name: 'Radio.js', type: 'component', level: 1 },
            { name: 'temp-test.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'debug.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'experimental.js', type: 'file', level: 1, duplicate: true, problematic: 'temp' },
            { name: 'backup.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'old-code.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'legacy.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'unused.js', type: 'file', level: 1, duplicate: true, problematic: 'abandoned' },
            { name: 'dont-delete.js', type: 'file', level: 1, duplicate: true, problematic: 'problematic' },
            { name: 'broken.js', type: 'file', level: 1, duplicate: true, problematic: 'problematic' },
            { name: 'fix-later.js', type: 'file', level: 1, duplicate: true, problematic: 'problematic' }
        ]
    ],
    organized: [
        // Month 1 - Clean organized start (8 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 2 - Adding structure (11 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 }
        ],
        // Month 4 - Growing with discipline (16 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 6
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 9
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'UserProfile/', type: 'folder', level: 2 },
            { name: 'UserProfile.jsx', type: 'component', level: 3 },
            { name: 'Dashboard/', type: 'folder', level: 2 },
            { name: 'Dashboard.jsx', type: 'component', level: 3 },
            { name: 'Modal/', type: 'folder', level: 2 },
            { name: 'Modal.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'userService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'constants.js', type: 'config', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 12
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'UserProfile/', type: 'folder', level: 2 },
            { name: 'UserProfile.jsx', type: 'component', level: 3 },
            { name: 'Dashboard/', type: 'folder', level: 2 },
            { name: 'Dashboard.jsx', type: 'component', level: 3 },
            { name: 'Modal/', type: 'folder', level: 2 },
            { name: 'Modal.jsx', type: 'component', level: 3 },
            { name: 'Settings/', type: 'folder', level: 2 },
            { name: 'Settings.jsx', type: 'component', level: 3 },
            { name: 'Sidebar/', type: 'folder', level: 2 },
            { name: 'Sidebar.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'userService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'authUtils.js', type: 'file', level: 2 },
            { name: 'validation.js', type: 'file', level: 2 },
            { name: 'constants.js', type: 'config', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 },
            { name: 'theme.config.js', type: 'config', level: 2 }
        ],
        // Month 18 - Well-organized scale (42 files)
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'UserProfile/', type: 'folder', level: 2 },
            { name: 'UserProfile.jsx', type: 'component', level: 3 },
            { name: 'Dashboard/', type: 'folder', level: 2 },
            { name: 'Dashboard.jsx', type: 'component', level: 3 },
            { name: 'Modal/', type: 'folder', level: 2 },
            { name: 'Modal.jsx', type: 'component', level: 3 },
            { name: 'Settings/', type: 'folder', level: 2 },
            { name: 'Settings.jsx', type: 'component', level: 3 },
            { name: 'Sidebar/', type: 'folder', level: 2 },
            { name: 'Sidebar.jsx', type: 'component', level: 3 },
            { name: 'SearchPage/', type: 'folder', level: 2 },
            { name: 'SearchPage.jsx', type: 'component', level: 3 },
            { name: 'Filters/', type: 'folder', level: 2 },
            { name: 'Filters.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'userService.js', type: 'file', level: 3 },
            { name: 'searchService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'authUtils.js', type: 'file', level: 2 },
            { name: 'validation.js', type: 'file', level: 2 },
            { name: 'searchUtils.js', type: 'file', level: 2 },
            { name: 'pagination.js', type: 'file', level: 2 },
            { name: 'constants.js', type: 'config', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 },
            { name: 'theme.config.js', type: 'config', level: 2 },
            { name: 'search.config.js', type: 'config', level: 2 }
        ]
    ]
};

