// Timeline data showing project growth over time
const timelineData = {
    messy: [
        // Month 1
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 }
        ],
        // Month 3
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 }
        ],
        // Month 6
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'api-helpers.js', type: 'file', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 }
        ],
        // Month 9
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'api-helpers.js', type: 'file', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-service.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'more-styles.css', type: 'file', level: 1 },
            { name: 'constants.js', type: 'config', level: 1 }
        ],
        // Month 12
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'api-helpers.js', type: 'file', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-service.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'more-styles.css', type: 'file', level: 1 },
            { name: 'constants.js', type: 'config', level: 1 },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'theme.css', type: 'file', level: 1 }
        ],
        // Month 18
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'App.js', type: 'file', level: 1 },
            { name: 'Button.js', type: 'component', level: 1 },
            { name: 'utils.js', type: 'file', level: 1 },
            { name: 'styles.css', type: 'file', level: 1 },
            { name: 'Header.js', type: 'component', level: 1 },
            { name: 'HomePage.js', type: 'component', level: 1 },
            { name: 'api-calls.js', type: 'file', level: 1 },
            { name: 'data.js', type: 'file', level: 1 },
            { name: 'helpers.js', type: 'file', level: 1 },
            { name: 'LoginForm.js', type: 'component', level: 1 },
            { name: 'config.js', type: 'config', level: 1 },
            { name: 'UserProfile.js', type: 'component', level: 1 },
            { name: 'api-helpers.js', type: 'file', level: 1 },
            { name: 'form-utils.js', type: 'file', level: 1 },
            { name: 'Dashboard.js', type: 'component', level: 1 },
            { name: 'Modal.js', type: 'component', level: 1 },
            { name: 'utils2.js', type: 'file', level: 1, duplicate: true },
            { name: 'api-service.js', type: 'file', level: 1 },
            { name: 'helpers2.js', type: 'file', level: 1, duplicate: true },
            { name: 'more-styles.css', type: 'file', level: 1 },
            { name: 'constants.js', type: 'config', level: 1 },
            { name: 'Settings.js', type: 'component', level: 1 },
            { name: 'Sidebar.js', type: 'component', level: 1 },
            { name: 'auth-utils.js', type: 'file', level: 1 },
            { name: 'form-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'validation.js', type: 'file', level: 1 },
            { name: 'theme.css', type: 'file', level: 1 },
            { name: 'SearchPage.js', type: 'component', level: 1 },
            { name: 'Filters.js', type: 'component', level: 1 },
            { name: 'utils3.js', type: 'file', level: 1, duplicate: true },
            { name: 'search-helpers.js', type: 'file', level: 1, duplicate: true },
            { name: 'pagination.js', type: 'file', level: 1 },
            { name: 'sorting.js', type: 'file', level: 1 },
            { name: 'filters-data.js', type: 'file', level: 1 },
            { name: 'search-config.js', type: 'config', level: 1 }
        ]
    ],
    organized: [
        // Month 1
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 3
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 6
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 9
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'UserProfile/', type: 'folder', level: 2 },
            { name: 'UserProfile.jsx', type: 'component', level: 3 },
            { name: 'Dashboard/', type: 'folder', level: 2 },
            { name: 'Dashboard.jsx', type: 'component', level: 3 },
            { name: 'Modal/', type: 'folder', level: 2 },
            { name: 'Modal.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'userService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'constants.js', type: 'config', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 }
        ],
        // Month 12
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'UserProfile/', type: 'folder', level: 2 },
            { name: 'UserProfile.jsx', type: 'component', level: 3 },
            { name: 'Dashboard/', type: 'folder', level: 2 },
            { name: 'Dashboard.jsx', type: 'component', level: 3 },
            { name: 'Modal/', type: 'folder', level: 2 },
            { name: 'Modal.jsx', type: 'component', level: 3 },
            { name: 'Settings/', type: 'folder', level: 2 },
            { name: 'Settings.jsx', type: 'component', level: 3 },
            { name: 'Sidebar/', type: 'folder', level: 2 },
            { name: 'Sidebar.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'userService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'authUtils.js', type: 'file', level: 2 },
            { name: 'validation.js', type: 'file', level: 2 },
            { name: 'constants.js', type: 'config', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 },
            { name: 'theme.config.js', type: 'config', level: 2 }
        ],
        // Month 18
        [
            { name: 'src', type: 'folder', level: 0 },
            { name: 'components/', type: 'folder', level: 1 },
            { name: 'Button/', type: 'folder', level: 2 },
            { name: 'Button.jsx', type: 'component', level: 3 },
            { name: 'Button.styles.js', type: 'file', level: 3 },
            { name: 'Button.test.js', type: 'file', level: 3 },
            { name: 'Header/', type: 'folder', level: 2 },
            { name: 'Header.jsx', type: 'component', level: 3 },
            { name: 'Header.styles.js', type: 'file', level: 3 },
            { name: 'LoginForm/', type: 'folder', level: 2 },
            { name: 'LoginForm.jsx', type: 'component', level: 3 },
            { name: 'LoginForm.styles.js', type: 'file', level: 3 },
            { name: 'UserProfile/', type: 'folder', level: 2 },
            { name: 'UserProfile.jsx', type: 'component', level: 3 },
            { name: 'Dashboard/', type: 'folder', level: 2 },
            { name: 'Dashboard.jsx', type: 'component', level: 3 },
            { name: 'Modal/', type: 'folder', level: 2 },
            { name: 'Modal.jsx', type: 'component', level: 3 },
            { name: 'Settings/', type: 'folder', level: 2 },
            { name: 'Settings.jsx', type: 'component', level: 3 },
            { name: 'Sidebar/', type: 'folder', level: 2 },
            { name: 'Sidebar.jsx', type: 'component', level: 3 },
            { name: 'SearchPage/', type: 'folder', level: 2 },
            { name: 'SearchPage.jsx', type: 'component', level: 3 },
            { name: 'Filters/', type: 'folder', level: 2 },
            { name: 'Filters.jsx', type: 'component', level: 3 },
            { name: 'pages/', type: 'folder', level: 1 },
            { name: 'HomePage/', type: 'folder', level: 2 },
            { name: 'HomePage.jsx', type: 'component', level: 3 },
            { name: 'HomePage.hooks.js', type: 'file', level: 3 },
            { name: 'services/', type: 'folder', level: 1 },
            { name: 'api/', type: 'folder', level: 2 },
            { name: 'apiService.js', type: 'file', level: 3 },
            { name: 'authService.js', type: 'file', level: 3 },
            { name: 'userService.js', type: 'file', level: 3 },
            { name: 'searchService.js', type: 'file', level: 3 },
            { name: 'utils/', type: 'folder', level: 1 },
            { name: 'helpers.js', type: 'file', level: 2 },
            { name: 'formUtils.js', type: 'file', level: 2 },
            { name: 'authUtils.js', type: 'file', level: 2 },
            { name: 'validation.js', type: 'file', level: 2 },
            { name: 'searchUtils.js', type: 'file', level: 2 },
            { name: 'pagination.js', type: 'file', level: 2 },
            { name: 'constants.js', type: 'config', level: 2 },
            { name: 'config/', type: 'folder', level: 1 },
            { name: 'app.config.js', type: 'config', level: 2 },
            { name: 'theme.config.js', type: 'config', level: 2 },
            { name: 'search.config.js', type: 'config', level: 2 }
        ]
    ]
};

